#!/bin/bash

go run ./cmd/root.go component apply -l ./config/components -c airship-email
go run ./cmd/root.go component apply -l ./config/components -c amymone
go run ./cmd/root.go component apply -l ./config/components -c analytics-service
go run ./cmd/root.go component apply -l ./config/components -c appstore-connect-iap-api
go run ./cmd/root.go component apply -l ./config/components -c archive
go run ./cmd/root.go component apply -l ./config/components -c article-intelligence
go run ./cmd/root.go component apply -l ./config/components -c article-service
go run ./cmd/root.go component apply -l ./config/components -c article-translator
go run ./cmd/root.go component apply -l ./config/components -c auth-api
go run ./cmd/root.go component apply -l ./config/components -c backstage
go run ./cmd/root.go component apply -l ./config/components -c banner-free
go run ./cmd/root.go component apply -l ./config/components -c betting-api
go run ./cmd/root.go component apply -l ./config/components -c betting-workers
go run ./cmd/root.go component apply -l ./config/components -c bookmarks
go run ./cmd/root.go component apply -l ./config/components -c campaign-manager
go run ./cmd/root.go component apply -l ./config/components -c category-tiles
go run ./cmd/root.go component apply -l ./config/components -c cdp-api
go run ./cmd/root.go component apply -l ./config/components -c cheburashka
go run ./cmd/root.go component apply -l ./config/components -c clips-api
go run ./cmd/root.go component apply -l ./config/components -c clips-search
go run ./cmd/root.go component apply -l ./config/components -c clips-webhooks
go run ./cmd/root.go component apply -l ./config/components -c clips
go run ./cmd/root.go component apply -l ./config/components -c cloud-runtime-bot
go run ./cmd/root.go component apply -l ./config/components -c competition-sorting-api
go run ./cmd/root.go component apply -l ./config/components -c consumer-web-v2
go run ./cmd/root.go component apply -l ./config/components -c consumer-web-v3
go run ./cmd/root.go component apply -l ./config/components -c content-classifier
go run ./cmd/root.go component apply -l ./config/components -c content-recommender
go run ./cmd/root.go component apply -l ./config/components -c content-tags-api
go run ./cmd/root.go component apply -l ./config/components -c creators-content
go run ./cmd/root.go component apply -l ./config/components -c creators-network
go run ./cmd/root.go component apply -l ./config/components -c daily-digest
go run ./cmd/root.go component apply -l ./config/components -c editorjs-translator
go run ./cmd/root.go component apply -l ./config/components -c emelya
go run ./cmd/root.go component apply -l ./config/components -c entity-index-api
go run ./cmd/root.go component apply -l ./config/components -c entity-resolution
go run ./cmd/root.go component apply -l ./config/components -c entity-service
go run ./cmd/root.go component apply -l ./config/components -c experimental-thumbor
go run ./cmd/root.go component apply -l ./config/components -c external-highlights
go run ./cmd/root.go component apply -l ./config/components -c facts-api
go run ./cmd/root.go component apply -l ./config/components -c facts-fetcher
go run ./cmd/root.go component apply -l ./config/components -c facts-importer
go run ./cmd/root.go component apply -l ./config/components -c fanmatch-go
go run ./cmd/root.go component apply -l ./config/components -c feeditem-algolia-indexer
go run ./cmd/root.go component apply -l ./config/components -c follower-count-publisher
go run ./cmd/root.go component apply -l ./config/components -c funtik
go run ./cmd/root.go component apply -l ./config/components -c gam-mrss-generator
go run ./cmd/root.go component apply -l ./config/components -c geoip
go run ./cmd/root.go component apply -l ./config/components -c gitleaks-api
go run ./cmd/root.go component apply -l ./config/components -c happy-keldysh
go run ./cmd/root.go component apply -l ./config/components -c idp-wrapper
go run ./cmd/root.go component apply -l ./config/components -c image-service
go run ./cmd/root.go component apply -l ./config/components -c image-uploader
go run ./cmd/root.go component apply -l ./config/components -c kuzya
go run ./cmd/root.go component apply -l ./config/components -c lead-gen-campaign-manager-web
go run ./cmd/root.go component apply -l ./config/components -c lead-gen-campaign-manager
go run ./cmd/root.go component apply -l ./config/components -c lead-gen-campaign-web
go run ./cmd/root.go component apply -l ./config/components -c lead-gen-data-collector-api
go run ./cmd/root.go component apply -l ./config/components -c librarian
go run ./cmd/root.go component apply -l ./config/components -c live-ticker-api
go run ./cmd/root.go component apply -l ./config/components -c live-ticker-importer
go run ./cmd/root.go component apply -l ./config/components -c loyalty-service
go run ./cmd/root.go component apply -l ./config/components -c mediation-api
go run ./cmd/root.go component apply -l ./config/components -c network-admin-api
go run ./cmd/root.go component apply -l ./config/components -c news
go run ./cmd/root.go component apply -l ./config/components -c newsdesk-admin-web
go run ./cmd/root.go component apply -l ./config/components -c neznaika
go run ./cmd/root.go component apply -l ./config/components -c not-found-server
go run ./cmd/root.go component apply -l ./config/components -c onboarding-api
go run ./cmd/root.go component apply -l ./config/components -c oncall-compensation
go run ./cmd/root.go component apply -l ./config/components -c onefootball-copilot
go run ./cmd/root.go component apply -l ./config/components -c optimistic-joliot
go run ./cmd/root.go component apply -l ./config/components -c ott-api
go run ./cmd/root.go component apply -l ./config/components -c ott-external-accounts
go run ./cmd/root.go component apply -l ./config/components -c ott-live-sessions
go run ./cmd/root.go component apply -l ./config/components -c ott-load-test-proxy
go run ./cmd/root.go component apply -l ./config/components -c ott-mediation
go run ./cmd/root.go component apply -l ./config/components -c ott-probe
go run ./cmd/root.go component apply -l ./config/components -c payments-history
go run ./cmd/root.go component apply -l ./config/components -c personalisation-service
go run ./cmd/root.go component apply -l ./config/components -c photobooth
go run ./cmd/root.go component apply -l ./config/components -c polls-api
go run ./cmd/root.go component apply -l ./config/components -c prometheus-exporter
go run ./cmd/root.go component apply -l ./config/components -c promo
go run ./cmd/root.go component apply -l ./config/components -c push-notification-center
go run ./cmd/root.go component apply -l ./config/components -c push
go run ./cmd/root.go component apply -l ./config/components -c quiz-api
go run ./cmd/root.go component apply -l ./config/components -c relevance-service
go run ./cmd/root.go component apply -l ./config/components -c replay-api
go run ./cmd/root.go component apply -l ./config/components -c resolver-api
go run ./cmd/root.go component apply -l ./config/components -c rich-push
go run ./cmd/root.go component apply -l ./config/components -c rss-generator
go run ./cmd/root.go component apply -l ./config/components -c score-api
go run ./cmd/root.go component apply -l ./config/components -c scores-mixer
go run ./cmd/root.go component apply -l ./config/components -c search-gateway-api
go run ./cmd/root.go component apply -l ./config/components -c seasons-cache
go run ./cmd/root.go component apply -l ./config/components -c simple-service
go run ./cmd/root.go component apply -l ./config/components -c sitemap-generator-v2
go run ./cmd/root.go component apply -l ./config/components -c specialone-slackbot
go run ./cmd/root.go component apply -l ./config/components -c stories-api
go run ./cmd/root.go component apply -l ./config/components -c streaming-service
go run ./cmd/root.go component apply -l ./config/components -c tv-guide-api
go run ./cmd/root.go component apply -l ./config/components -c tv-guide-importer
go run ./cmd/root.go component apply -l ./config/components -c umka
go run ./cmd/root.go component apply -l ./config/components -c users-accounts-api
go run ./cmd/root.go component apply -l ./config/components -c users-auth-api
go run ./cmd/root.go component apply -l ./config/components -c users-gdpr
go run ./cmd/root.go component apply -l ./config/components -c users-pii
go run ./cmd/root.go component apply -l ./config/components -c vinnipuh
go run ./cmd/root.go component apply -l ./config/components -c watch
go run ./cmd/root.go component apply -l ./config/components -c web-experience
go run ./cmd/root.go component apply -l ./config/components -c web-payments-backend
go run ./cmd/root.go component apply -l ./config/components -c web-url-redirector
go run ./cmd/root.go component apply -l ./config/components -c web3-transactions
go run ./cmd/root.go component apply -l ./config/components -c webhook-receiver
go run ./cmd/root.go component apply -l ./config/components -c webserver
go run ./cmd/root.go component apply -l ./config/components -c ws-receiver
go run ./cmd/root.go component apply -l ./config/components -c xpa-backend
go run ./cmd/root.go component apply -l ./config/components -c xpa-mobile-backend
go run ./cmd/root.go component apply -l ./config/components -c xpa-tv-backend
