apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: daily-digest
    componentType: service
spec:
    name: daily-digest
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn:
        - apple-news
        - news
    tribe: reach
    squad: fan-activation
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/daily-digest
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=daily-digest&var-container=daily-digest&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
    labels:
        - reach
        - fan-activation
