---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: security
spec:
  name: security
  description: "https://github.com/motain/of-catalog/blob/main/docs/grading-system/security.md#security-grading-system"
  ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
  state: "PUBLISHED" # DRAFT - PUBLISHED
  componentTypeIds: ["SERVICE"]
  importance: REQUIRED
  scoringStrategyType: "WEIGHT_BASED" # WEIGHT_BASED - POINT_BASED
  criteria:
    - hasMetricValue:
        weight: 50
        name: security-as-pipeline
        metricName: security-as-pipeline
        comparatorValue: 1
        comparator: "EQUALS" # EQUALS - GREATER_THAN - LESS_THAN - GREATER_THAN_OR_EQUAL_TO - LESS_THAN_OR_EQUAL_TO
    - hasMetricValue:
        weight: 50
        name: vulnerability-management
        metricName: vulnerability-management
        comparatorValue: 1
        comparator: "LESS_THAN" # EQUALS - GREATER_THAN - LESS_THAN - GREATER_THAN_OR_EQUAL_TO - LESS_THAN_OR_EQUAL_TO
