---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: ott-external-accounts-tf
    componentType: cloud-resource
spec:
  name: 'ott-external-accounts-tf'
  description: RDS cluster used by ott-external-accounts.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/ott-external-accounts/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=ott-external-accounts-tf;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "engagement", "live-video", "ott-external-accounts", "aurora-postgresql"]
  customFields: null

