---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: facts
    componentType: cloud-resource
spec:
  name: 'facts'
  description: RDS cluster used by facts.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/facts/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=facts;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "engagement", "matchxp", "facts", "aurora-mysql"]
  customFields: null

