---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: content-classifier-tf
    componentType: cloud-resource
spec:
  name: 'content-classifier-tf'
  description: RDS cluster used by content-classifier.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/content-classifier"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=content-classifier-tf;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "engagement", "personalisation", "content-classifier", "aurora-postgresql"]
  customFields: null

