---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: banner-free-tf
    componentType: cloud-resource
spec:
  name: 'banner-free-tf'
  description: RDS cluster used by banner-free.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/banner-free/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=banner-free-tf;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "monetization", "media-advertising", "banner-free", "aurora-postgresql"]
  customFields: null

