---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: betting-prod
    componentType: cloud-resource
spec:
  name: 'betting-prod'
  description: RDS cluster used by betting-api.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/betting-api/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=betting-prod;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "monetization", "sponsorship-integration", "betting-api", "aurora-mysql"]
  customFields: null

