---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: lead-gen-prod
    componentType: cloud-resource
spec:
  name: 'lead-gen-prod'
  description: RDS cluster used by lead-gen-data-collector.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/lead-gen-prod/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=lead-gen-prod;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "monetization", "sponsorship-integration", "lead-gen-data-collector", "aurora-postgresql"]
  customFields: null

