---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: users-accounts-tf
    componentType: cloud-resource
spec:
  name: 'users-accounts-tf'
  description: RDS cluster used by users-accounts-pi.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/users-accounts-api/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=users-accounts-tf;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "reach", "fan-activation", "users-accounts-pi", "aurora-postgresql"]
  customFields: null

