---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: tvguide
    componentType: cloud-resource
spec:
  name: 'tvguide'
  description: RDS cluster used by tv-guide-api.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/tvguide/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=tvguide;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "monetization", "sponsorship-integration", "tv-guide-api", "aurora-mysql"]
  customFields: null

