---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: streaming-service-tf
    componentType: cloud-resource
spec:
  name: 'streaming-service-tf'
  description: RDS cluster used by streaming-service.
  typeId: CLOUD_RESOURCE
  fields:
    tier: 4
    isMonorepoProject: true
  links:
    - name: Repository
      type: REPOSITORY
      url: "https://github.com/motain/iac/blob/master/production/applications/streaming-service/rds"
    - name: Monitoring page
      type: DASHBOARD
      url: "https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=streaming-service-tf;is-cluster=true;tab=monitoring"
  relationships: {}
  labels: ["aws", "rds", "engagement", "live-video", "streaming-service", "aurora-postgresql"]
  customFields: null

