// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apply

import (
	"github.com/google/wire"
	"github.com/motain/of-catalog/internal/modules/component/handler"
	"github.com/motain/of-catalog/internal/modules/component/repository"
	"github.com/motain/of-catalog/internal/services/compassservice"
	"github.com/motain/of-catalog/internal/services/configservice"
	"github.com/motain/of-catalog/internal/services/documentservice"
	"github.com/motain/of-catalog/internal/services/githubservice"
	"github.com/motain/of-catalog/internal/services/keyringservice"
	"github.com/motain/of-catalog/internal/services/ownerservice"
	"github.com/motain/of-catalog/internal/services/prometheusservice"
)

// Injectors from wire.go:

func initializeHandler() *handler.ApplyHandler {
	configService := configservice.NewConfigService()
	keyringService := keyringservice.NewKeyringService()
	gitHubClientInterface := githubservice.NewGitHubClient(configService, keyringService)
	gitHubService := githubservice.NewGitHubService(gitHubClientInterface)
	graphQLClientInterface := compassservice.NewGraphQLClient(configService)
	httpClientInterface := compassservice.NewHTTPClient(configService)
	compassService := compassservice.NewCompassService(configService, graphQLClientInterface, httpClientInterface)
	repositoryRepository := repository.NewRepository(compassService)
	ownerService := ownerservice.NewOwnerService(gitHubService)
	documentService := documentservice.NewDocumentService(gitHubService)
	applyHandler := handler.NewApplyHandler(gitHubService, repositoryRepository, ownerService, documentService)
	return applyHandler
}

// wire.go:

var ProviderSet = wire.NewSet(keyringservice.NewKeyringService, wire.Bind(new(keyringservice.KeyringServiceInterface), new(*keyringservice.KeyringService)), configservice.NewConfigService, wire.Bind(new(configservice.ConfigServiceInterface), new(*configservice.ConfigService)), compassservice.NewGraphQLClient, compassservice.NewHTTPClient, compassservice.NewCompassService, wire.Bind(new(compassservice.CompassServiceInterface), new(*compassservice.CompassService)), githubservice.NewGitHubClient, githubservice.NewGitHubService, wire.Bind(new(githubservice.GitHubServiceInterface), new(*githubservice.GitHubService)), prometheusservice.NewPrometheusService, prometheusservice.NewPrometheusClient, wire.Bind(new(prometheusservice.PrometheusServiceInterface), new(*prometheusservice.PrometheusService)), ownerservice.NewOwnerService, wire.Bind(new(ownerservice.OwnerServiceInterface), new(*ownerservice.OwnerService)), documentservice.NewDocumentService, wire.Bind(new(documentservice.DocumentServiceInterface), new(*documentservice.DocumentService)), repository.NewRepository, wire.Bind(new(repository.RepositoryInterface), new(*repository.Repository)), handler.NewApplyHandler)
