// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apply

import (
	"github.com/google/wire"
	"github.com/motain/of-catalog/internal/modules/metric/handler"
	"github.com/motain/of-catalog/internal/modules/metric/repository"
	"github.com/motain/of-catalog/internal/services/compassservice"
	"github.com/motain/of-catalog/internal/services/configservice"
	"github.com/motain/of-catalog/internal/services/githubservice"
	"github.com/motain/of-catalog/internal/services/keyringservice"
)

// Injectors from wire.go:

func initializeHandler() *handler.ApplyHandler {
	configService := configservice.NewConfigService()
	graphQLClientInterface := compassservice.NewGraphQLClient(configService)
	httpClientInterface := compassservice.NewHTTPClient(configService)
	compassService := compassservice.NewCompassService(configService, graphQLClientInterface, httpClientInterface)
	repositoryRepository := repository.NewRepository(compassService)
	applyHandler := handler.NewApplyHandler(repositoryRepository)
	return applyHandler
}

// wire.go:

var ProviderSet = wire.NewSet(keyringservice.NewKeyringService, wire.Bind(new(keyringservice.KeyringServiceInterface), new(*keyringservice.KeyringService)), configservice.NewConfigService, wire.Bind(new(configservice.ConfigServiceInterface), new(*configservice.ConfigService)), compassservice.NewGraphQLClient, compassservice.NewHTTPClient, compassservice.NewCompassService, wire.Bind(new(compassservice.CompassServiceInterface), new(*compassservice.CompassService)), githubservice.NewGitHubClient, githubservice.NewGitHubService, wire.Bind(new(githubservice.GitHubServiceInterface), new(*githubservice.GitHubService)), repository.NewRepository, wire.Bind(new(repository.RepositoryInterface), new(*repository.Repository)), handler.NewApplyHandler)
